name: GitHub Organization Terraform
on:
  push:
    branches:
      - master
    paths:
      - tools/github/organization/*
  pull_request:
    branches:
      - master
    paths:
      - tools/github/organization/*

defaults:
  run:
    shell: bash
    working-directory: tools/github/organization

env:
  GITHUB_TOKEN: ${{ secrets.MACHINE_USER_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: "ap-northeast-1"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get terraform version
        id: tfver
        run: echo "::set-output name=tfver::`cat $GITHUB_WORKSPACE/.terraform-version`"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.tfver.outputs.tfver }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -refresh=false -compact-warnings

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve -refresh=false -compact-warnings
